setwd("D:/Program Files/Theorem Factory/choice")
readed_translated_style <- scan("name_readed_translated_style.txt",what="character", sep=" ")
readed_translated_style <- readed_translated_style[3]
readed_translated_style <- sub("FirstName","A",readed_translated_style)
readed_translated_style <- sub("MiddleName","N",readed_translated_style)
readed_translated_style <- sub("LastName","Skiba",readed_translated_style)
readed_translated_style <- sub("paper","On the conditions of cyclic $G$-major factors of normal subgroups of $G$",readed_translated_style)
readed_translated_style <- sub("jour","Siberian Math. J",readed_translated_style)
readed_translated_style <- sub("vol","52",readed_translated_style)
readed_translated_style <- sub("issue","1",readed_translated_style)
readed_translated_style <- sub("year","2011",readed_translated_style)
readed_translated_style <- sub("pages","127-130",readed_translated_style)
setwd("D:/Program Files/Theorem Factory/text_output_documents")
nameofoutput <-  " output_style "
nameofoutput <- gsub(" ","",nameofoutput)
nameofoutput <- paste(nameofoutput,".txt",sep = "")
fileConn4<-file(nameofoutput)
writeLines(readed_translated_style, fileConn4)
close(fileConn4)
